-- Rollback migration 040
ALTER TABLE property_charges
  DROP COLUMN IF EXISTS taxe_habitation,
  DROP COLUMN IF EXISTS taxe_logements_vacants,
  DROP COLUMN IF EXISTS teom,
  DROP COLUMN IF EXISTS insurance_gli_eur,
  DROP COLUMN IF EXISTS insurance_gli_pct,
  DROP COLUMN IF EXISTS insurance_mrh,
  DROP COLUMN IF EXISTS condo_fees_works,
  DROP COLUMN IF EXISTS condo_special_fund,
  DROP COLUMN IF EXISTS management_agency_eur,
  DROP COLUMN IF EXISTS management_agency_pct,
  DROP COLUMN IF EXISTS management_airbnb_pct,
  DROP COLUMN IF EXISTS management_booking_pct,
  DROP COLUMN IF EXISTS management_cleaning,
  DROP COLUMN IF EXISTS management_concierge,
  DROP COLUMN IF EXISTS maintenance_major,
  DROP COLUMN IF EXISTS repairs_provision,
  DROP COLUMN IF EXISTS legal_fees,
  DROP COLUMN IF EXISTS diagnostics_fees,
  DROP COLUMN IF EXISTS utilities_internet,
  DROP COLUMN IF EXISTS utilities_electricity,
  DROP COLUMN IF EXISTS utilities_water,
  DROP COLUMN IF EXISTS other_note;
